### ISSUE TITLE
implementation timeline

### ISSUE THREAD

**Issue by easchwar** [TylerAckerson/seinfood#1]
Phase 1: shouldn't need to make user `edit` or `show` views on the rails end. The only views you'll probably need are `root` `users/new` and `session/new`. 
If you want to be able to see a user's profile, make it a React view. That way you can just have the home page show user relevant information. 

Phase 2: I would probably move the google maps API into its own phase, or at least move it to the very end of phase 2. Don't worry too much about seed data this early on. The core functionality should take precedence. Good flux architecture.

Phase 3: Nice.

Phase 4: I wouldn't even fake it with the credit card validation. You could just make everything on the house or something like that.

Phase 5: I like the polymorphic association, but be careful on adding too much functionality to the MVP. Favoriting things can be tricky. Maybe make phase 5 just Past Orders, and move Favorites to bonus?

Phase 6: Just be careful not to leave _all_ the styling to the end.

**Comment by tylerackerson** [comment]
Updates made. Thanks for the thorough feedback
