### ISSUE TITLE
db schema

### ISSUE THREAD

**Issue by easchwar** [TylerAckerson/seinfood#2]
Restaurants - Too much information. Make it simple to start. Compress the delivery and take_out columns into one set. Storing all the days in a single column is gonna be shitty. To start just assume open all 7 days. Only record opening and closing hours. Move everything else into bonus.

Menu Items - Make `id` the only primary key.

Orders - `date` is unnecessary; you can just use the timestamps or combine it with `scheduled_for`. For all of your fees, at least 2 of them shouldn't be stored on the order. `total` is calculatable. `tax` isn't a property of an order, and so it shouldn't be stored there.

Order Items - `notes` should be `text` not string

Reviews - `body` should be `text`

**Comment by tylerackerson** [comment]
Updated
